### ISSUE TITLE
zambretti formula

### ISSUE THREAD

**Issue by thibautsergent** [G6EJD/ESP32_Weather_Forecaster_TN061#1]
Hi,

What a great work ! 👍 

I would like to know how did you get the zamberetti formula ?

Thanks

**Comment by G6EJD** [comment]
I have an original Zambretti forecaster made in 1920 it’s a bit like a slide rule, from which it is easy to reverse engineer the method. The original calculator uses inches of air pressure and needs to know whether pressure is steady, rising or falling plus ideally wind direction, but I found wind direction makes little difference to the outcome. The Zambretti method is still about 90% accurate in its forecasts. When I’m better I’ll produce a video on the subject.
