### ISSUE TITLE
Zambretti's Algorithm 

### ISSUE THREAD

**Issue by lcfelippe** [G6EJD/ESP32_Weather_Forecaster_TN061#2]
Hi Dave,

Reading some documentation about Zambretti in the web, i found the the following formula:

If the pressure is falling compute the forecast number as Z=130−P0/81

If the pressure is steady compute the forecast number as Z=147−5P0/376

If the pressure is rising compute the forecast number as Z = 179 - 2 * P0/129

How did you get the algorithm that you use in your code?

Thanks

**Comment by G6EJD** [comment]
Hi ,
 
Well, I have an original 1915 Zambretti forecaster (really it’s an early form of slide rule in a circular form). The main dial is set by the current air pressure and optionally wind direction and for a rising, falling or steady pressure these are converted to a letter between A to Z each represents a forecast. by looking at the reverse. It is easy to plot the relationship between air pressure and the letters and all three relationships are a near straight line equation, but there are some perturbations and to replicate in software the transfer function can be determined for all three functions by a best fit line, and this is what I did. the resultant formulas then represent the best fit based on the original Zambretti forecaster. You can use an approximation but the results are variable.

My formulas match the Zambretti perfectly.

I have an ESP32 asked version running on batteries for the last year and it’s very accurate, I’d say >95%.

Hopes this helps.
 
Regards

David

**Comment by lcfelippe** [comment]
Cool, i'll try it on my project. Another question is about the compensation of Summer and Winter. The Zambretti documentation's says that on Summer Rising , the Z number improves the prospect in 1 unit, and on Winter Falling, the Z number is lower to 1 unit. Why are you compensate te Z number to +1 in all cases?. The right way wouldn't be:?

Winter Z=Z+1 

Summer Z=Z-1

Font: http://integritext.net/DrKFS/zambretti.htm

When it's possible, could you make a video about Zambretti Algorithms and forecast?, and show how the original Zambretti's forecast Disc works?

Thanks David.

Regards…

**Comment by G6EJD** [comment]
i’ll need to get my Zambretti our to check why Z is being modified. Yes I’ll try and make a video on the forecaster. 

What is the specific issue your are reporting here?

**Comment by lcfelippe** [comment]
I'm working on my weather Station and get most inaccurate Zambretti forecaster, that's why I'm asking you about the formulas that you use and the season's Z compensation.

Regards...

**Comment by G6EJD** [comment]
The methods has been around a 100+ years and does work, there are a few java based online calculators that you can compare your results with, but I suspect you have a code error. in the southern hemisphere the results are inverted for summer/winter.

**Comment by lcfelippe** [comment]
I had already made the modifications to adapt the code to the Southern Hemisphere. here is my formulas:

```
 // Case trend is falling
  if (trend == -1) {
    float zambretti = (130 - equivalent_pressure_rounded) / 81;
    //A Winter falling generally results in a Z value lower by 1 unit
    if (month > 4 || month < 9) zambretti = zambretti + 1;  // Increase in 1 unit on Winter to compensate the derivation

// Case trend is steady
 if (trend == 0) {
    float zambretti = (147 - 5 * equivalent_pressure_rounded) / 376;

 // Case trend is rising
  if (trend == 1) {
    float zambretti = (179 - 2 * equivalent_pressure_rounded) / 129;
    //A Summer rising, improves the prospects by 1 unit over a Winter rising
    if (month >= 9 && month <= 4) zambretti = zambretti - 1;  // Decrease 1 unit on Summer to compensate the derivation
```

Use it as reference: http://integritext.net/DrKFS/zambretti.htm

**Comment by G6EJD** [comment]
it look ok. what i would do is generate some test cases such that you know from various on line resources what the result should be for given conditions say lowest pressure and steady and month = 3 and make sure your code does what’s expected, next test case month = 4 all other conditions the same now you should see a change in the Z number then repeat for ridings g and falling and then realest at air pressure maximum and so-on.

**Comment by lcfelippe** [comment]
Sorry if i lost something. Digging into your code i notice that you collect 24hs of pressure, for calculation of trend you use the last 3 hour (trend = reading[23] - reading[20]), and for Zambretti's number you use the reading[20] and the last 3 hour trend. Why you collect 24 hour data if you use only the last 3 hour?
I'll prepare some cases to test online and see if it will match to my code.

Regards,

**Comment by G6EJD** [comment]
Yes I use a number of techniques for collecting pressure trend, but use -4hrs and now for the Zambretti slope, I also show a trend arrow on the screen that’s the other slope and then I graph the last 24-hours of pressure trend. it takes a full 24-hours to accumulate a full graph. 

it’s better to email me direct than use Github as a chat forum, please do that via david.g6ejd@gmail.com
I don’t believe you have found any issues with my code so I’m closing this Issue.

**Comment by G6EJD** [comment]
I've made some improvements to the Zambretti calculator, including wind and North/Southern hemisphere, still under test, but much improved from my original.

**Comment by lcfelippe** [comment]
Very good improvement!. Please, let me know about the results. I'm wondering to do this on my Weather Station. 

Regards,

**Comment by G6EJD** [comment]
What I’ve done is reworked all of the equations and validated the results of each against the original Zambretti disc, and then included the wind offsets and winter/summer adjustments together with north and south hemisphere, I did this because the original code was lacking in these areas. The result is a much improved result. Only pressure and trend are required, others can be left blank.
